version: "3.8"

services:
  neo4j:
    image: neo4j:5.17
    container_name: neo4j-db
    environment:
      NEO4J_AUTH: "neo4j/password"
      NEO4J_server_memory_heap_initial__size: 512m
      NEO4J_server_memory_heap_max__size: 1g
      NEO4J_PLUGINS: '["apoc"]'
    ports:
      - "7474:7474" # HTTP
      - "7687:7687" # Bolt
    volumes:
      - ./data:/data
      - ./logs:/logs
      - ./plugins:/plugins
